spring:
  datasource:
    username: root
    password: 12345678
    url: jdbc:mysql//localhost:3306/sell?serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update

server:
  port: 5678
