spring:
  datasource:
    username: root
    password: 12345678
    url: jdbc:mysql://localhost:3306/sell?serverTimezone=UTC&useUnicode=true&characterEncoding=utf8&useSSL=false

    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    database: mysql
server:
  port: 5678
